apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: ./patches/fleet.yaml
  target:
    kind: Fleet
images:
- name: image
  newName: live-streaming-server-net-pod-demo
namespace: live-streaming-server-net
